spring:
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB
  data:
    mongodb:
      uri: "mongodb://Mugeon:1234@43.201.219.22:27017/CStudy"
  redis:
    host: 43.201.219.22
    port: 6379
  session:
    timeout: 600
    store-type: redis
    redis:
      flush-mode: on-save
      namespace: spring:session
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/CStudy?serverTimezone=Asia/Seoul
    username: root
    password: 1234
    hikari:
      connectionTimeout: 30000
      maximumPoolSize: 20
      maxLifetime: 295000
      poolName: HikariCP
      readOnly: false
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  mail:
    host: smtp.naver.com
    port: 465
    username: cstudy1234@naver.com
    password: cstudy1234!
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 105704828821-2vf7ui58dkt0dlr4e1n1dsmsqbvogg02.apps.googleusercontent.com
            client-secret: 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
            scope: profile,email
          naver:
            client-id: FFL4eXeGmyxGM1ZmchEY
            client-secret: TfpHeoDWEa
            redirect-uri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
            authorization-grant-type: authorization_code
            scope: name,email,profile_image
            client-name: Naver
          kakao:
            client-id: a3d6495c7a1eef1cd1850730e928e704
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: profile_nickname, profile_image, account_email
            client-name: Kakao

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id



server:
  tomcat:
    threads:
      max: 18
      min-spare: 18
    accept-count: 300
  port: 8080

jwt:
  secretKey: "0123456789012345678901234567890123456789"
  refreshKey: "0123456789012345678901234567890123456789"

cloud:
  aws:
    credentials:
      accessKey: "AKIATRTDCFAC5EBYZRE5"
      secretKey: "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"
    s3:
      bucket: j4j-test-bucket
    region:
      static: ap-northeast-2
    stack:
      auto: false


